import Ignite

/// The desktop with one window open and in front, served at that window's
/// path. Generated by `CocoaHeadsDesktop.pages`.
struct DesktopWindowPage: StaticPage {
    let title: String
    let path: String
    let windowID: String

    var body: some HTML {
        CocoaHeadsDesktop.desktop(opening: windowID)
    }
}
